%
% Generate a significance plot.  This plots an n*n matrix of pairwise
% comparisons between n methods.  The legend for this plot is
% generated by konect_significance_legend(). 
%
% PARAMETERS 
%	values	(m*n) Matrix of values; there are n methods with m
%		values each 
%	p_threshold
%	maxdiff
%	labels
%
% ABOUT 
%	This file is part of the KONECT Matlab Toolbox version 0.3.
%	konect.uni-koblenz.de
%	(c) Jerome Kunegis 2014; this is Free Software released under
%	the GPLv3, see COPYING. 
%

function konect_significance_plot(values, p_threshold, maxdiff, labels)

font_size = 13; 
displacement_x = 0.3; 
displacement_y = 0.2; 
rotation_y = 27;

[m n] = size(values);

% Pairwise p-values 
P = zeros(m, m); 

% Pairwise differences
D = zeros(m, m); 

for i = 1 : m
    for j = 1 : m
        [h p] = ttest(values(i, :), values(j, :)); 
        P(i, j) = p; 
        D(i, j) = mean(values(i,:) - values(j,:)); 
    end
end

P
D

I = konect_significance_image(P, D, p_threshold, maxdiff);

image(I);

% Labels
for i = 1 : m
    text(0+displacement_x, i  , labels(i), 'HorizontalAlignment', 'Right', 'VerticalAlignment', 'Middle', 'FontSize', font_size); 
    text(i, m+1-displacement_y, labels(i), 'HorizontalAlignment', 'Right', 'VerticalAlignment', 'Middle', 'FontSize', font_size, 'Rotation', rotation_y); 
end

% xticklabel_rotate(1:m, 90, labels, 'FontSize', font_size); 
% yticklabel_rotate(1:m,  0, labels, 'FontSize', font_size); 
set(gca, 'XTick', []); 
set(gca, 'YTick', []); 
%set(gca, 'TickLength', [0 0]); 
%set(gca, 'FontSize', font_size); 

% xlabel('Method j', 'FontSize', font_size);
% ylabel('Method i', 'FontSize', font_size); 

axis square; 
